export const worksData = [
  {
    index: 1,
    projectName: "SOCIALMATE",
    about: "A social media platfrom to share thougts",
    picture: "https://i.ibb.co/HxNqtZ2/Scresocialmate.png",
    features: [
      "This is a Social Media",
      "Users can share their thoughts by writing a post",
      "Users can add comments to any post ",
      "Users can like posts and also remove likes",
      "Users can log in, sign in, Forget their Password",
    ],
    tecnologies: [
      "React JS",
      "Tailwind CSS",
      "daisy-UI",

      "Json Web Token",
      "Node JS",
      "Express JS",
      "React-hot-toast",
    ],
    Specialty: "I am using  MongoDB for authentication first Time",

    liveSite: "https://social-mate.netlify.app/",
    clientSite: "https://github.com/mahmudur987/socialmate",
    serverSite: "https://github.com/mahmudur987/socialmate-server",
  },
  {
    index: 2,
    projectName: "Movie Hub",
    about: "A movie-watching platfrom",
    picture: "https://i.ibb.co/xjJvw7Z/movie-hub.png",
    features: [
      "this website is for watching movies in theaters.",
      "Users can book a ticket.",
      "User login and sign up.  ",
      "Users can see details of the movie.",
      "server site working remains.",
    ],
    tecnologies: [
      "React JS",
      "Tailwind CSS",
      "daisy-UI",

      "Json Web Token",
      "Node JS",
      "Express JS",
      "React-hot-toast",
    ],
    Specialty: "I am using  MongoDB for authentication first Time",

    liveSite: "https://movie-hub9.netlify.app/",
    clientSite: "https://github.com/mahmudur987/movie-hub",
    serverSite: "https://github.com/mahmudur987/movie-hub",
  },
  {
    index: 3,
    projectName: "Magazine",
    about: "A reading blog website.",
    picture: "https://i.ibb.co/G5h5rcn/magazine.png",
    features: [
      "A reading blog website.",
      "Users can read stories.",
      "user can Log in",
      "user can sign up.",
      "admin has a dashboard.",
      "admin can add a blog.",
      "admin can remove blog",
    ],
    tecnologies: [
      "React JS",
      "Tailwind CSS",
      "daisy-UI",
      "Redux",
      "React-hot-toast",
    ],
    Specialty: "Here I am using redux",

    liveSite: "https://movie-hub9.netlify.app/",
    clientSite: "https://github.com/mahmudur987/magazine",
    serverSite: "https://github.com/mahmudur987/magazine",
  },
  // {
  //   index: 4,
  //   projectName: "Magazine",
  //   about: "A reading blog website.",
  //   picture: "https://i.ibb.co/G5h5rcn/magazine.png",
  //   features: [
  //     "A reading blog website.",
  //     "Users can read stories.",
  //     "user can Log in",
  //     "user can sign up.",
  //     "admin has a dashboard.",
  //     "admin can add a blog.",
  //     "admin can remove blog",
  //   ],
  //   tecnologies: [
  //     "React JS",
  //     "Tailwind CSS",
  //     "daisy-UI",
  //     "Redux",
  //     "React-hot-toast",
  //   ],
  //   Specialty: "Here I am using redux",

  //   liveSite: "https://movie-hub9.netlify.app/",
  //   clientSite: "https://github.com/mahmudur987/magazine",
  //   serverSite: "https://github.com/mahmudur987/magazine",
  // },
];
