export const worksData = [
  {
    index: 1,
    projectName: "SOCIALMATE",
    about: "A social media platfrom to share thougts",
    picture: "https://i.ibb.co/HxNqtZ2/Scresocialmate.png",
    features: [
      "This is a Social Media",
      "Users can share their thoughts by writing a post",
      "Users can add comments to any post ",
      "Users can like posts and also remove likes",
      "Users can log in, sign in, Forget their Password",
    ],
    tecnologies: [
      "React JS",
      "Tailwind CSS",
      "daisy-UI",

      "Json Web Token",
      "Node JS",
      "Express JS",
      "React-hot-toast",
    ],
    Specialty: "I am using  MongoDB for authentication first Time",

    liveSite: "https://social-mate.netlify.app/",
    clientSite: "https://github.com/mahmudur987/socialmate",
    serverSite: "https://github.com/mahmudur987/socialmate-server",
  },
  {
    index: 2,
    projectName: "Movie Hub",
    about: "A movie-watching platfrom",
    picture: "https://i.ibb.co/xjJvw7Z/movie-hub.png",
    features: [
      "this website is for watching movies in theaters.",
      "Users can book a ticket.",
      "User login and sign up.  ",
      "Users can see details of the movie.",
      "server site working remains.",
    ],
    tecnologies: [
      "React JS",
      "Tailwind CSS",
      "daisy-UI",

      "Json Web Token",
      "Node JS",
      "Express JS",
      "React-hot-toast",
    ],
    Specialty: "I am using  MongoDB for authentication first Time",

    liveSite: "https://movie-hub9.netlify.app/",
    clientSite: "https://github.com/mahmudur987/movie-hub",
    serverSite: "https://github.com/mahmudur987/movie-hub",
  },
  {
    index: 3,
    projectName: "Magazine",
    about: "A reading blog website.",
    picture: "https://i.ibb.co/G5h5rcn/magazine.png",
    features: [
      "A reading blog website.",
      "Users can read stories.",
      "user can Log in",
      "user can sign up.",
      "admin has a dashboard.",
      "admin can add a blog.",
      "admin can remove blog",
    ],
    tecnologies: [
      "React JS",
      "Tailwind CSS",
      "daisy-UI",
      "Redux",
      "React-hot-toast",
    ],
    Specialty: "Here I am using redux",

    liveSite: "https://movie-hub9.netlify.app/",
    clientSite: "https://github.com/mahmudur987/magazine",
    serverSite: "https://github.com/mahmudur987/magazine",
  },
  {
    picture:
      "https://images.unsplash.com/photo-1523995462485-3d171b5c8fa9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=435&q=80",
    features: [
      " Online News Website",
      "News are sorting",
      "New News pulish leteast",
    ],
    tecnologies: [
      "React.js",
      "Tailwind CSS",
      "daisy-Ui",
      "Firebase",
      "Mongo Db",
      "Node.js",
      "Express.Js",
    ],

    projectName: "News OF NATION",
    Specialty: "Here I am using API",
    about: " a news published website ",
    discription:
      "Welcome to  Online News Portal, where news meets convenience. We understand the importance of staying informed in today's fast-paced world, and that's why we bring you a seamless online platform packed with the latest news and insights from around the globe. Here's what sets us apart",
    registered: "2022-05-09",
    liveSite: "https://newsofnation.netlify.app/",
    clientSite: "https://github.com/mahmudur987/news-portal-assign-6",
    serverSite: "",
  },

  {
    picture:
      "https://images.unsplash.com/photo-1472851294608-062f824d29cc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    features: ["Shopping Website", " Online buy ", "best Features"],
    tecnologies: [
      "React JS",
      "Tailwind CSS",
      "daisy-UI",

      "Json Web Token",
      "Node JS",
      "Express JS",
      "React-hot-toast",
    ],
    projectName: "Ema-jhon",
    about: "A  Online shop ",
    Specialty: "Here I am using Mongodb",
    discription:
      "At Emajhon , we redefine your shopping experience, bringing you a world of products at your fingertips. Discover a seamless blend of choice, convenience, and quality, all in one place. Here's why shopping with us is a delight",
    registered: "2022-04-09",
    liveSite: "https://ema-jhon-987.netlify.app/",
    clientSite: "https://github.com/mahmudur987/ema-jhon-repo",
    serverSite: "",
  },
  {
    index: 4,
    projectName: "Magazine",
    about: "A reading blog website.",
    picture: "https://i.ibb.co/G5h5rcn/magazine.png",
    features: [
      "A reading blog website.",
      "Users can read stories.",
      "user can Log in",
      "user can sign up.",
      "admin has a dashboard.",
      "admin can add a blog.",
      "admin can remove blog",
    ],
    tecnologies: [
      "React JS",
      "Tailwind CSS",
      "daisy-UI",
      "Redux",
      "React-hot-toast",
    ],
    Specialty: "Here I am using redux",

    liveSite: "https://magazine987.netlify.app/",
    clientSite: "https://github.com/mahmudur987/magazine",
    serverSite: "https://github.com/mahmudur987/magazine",
  },
];
